### ISSUE TITLE
feature request: Add priority order to watchers

### ISSUE THREAD

**Issue by Cian911** [Cian911/switchboard#22]
Each watcher should have a changeable priority which would denote which watcher should process an event in the case that multiple watchers match the same event. Take the example below.

I have the following config for switchboard:
```yaml
pollingInterval: 10
watchers:
  - path: "/home/cian/Downloads"
    destination: "/home/cian/Documents"
    ext: ".txt"
  - path: "/home/cian/Downloads"
    destination: "/home/cian/Documents/Reports"
    ext: ".txt"
    pattern: "(?i)(financial-report-[a-z]+-[0-9]+.txt)"
  - path: "/home/cian/Downloads"
    destination: "/home/cian/Videos"
    ext: ".mp4"
```

In the event that I save a `txt` file that matches the first two watchers, we encounter a race condition between the two as to which will process the event first.

I propose adding a _priority_ attribute to switchboard which will denote the order in which events should be processed by watchers, should multiple watchers be capable of matching the same event. A new config might look like this:

```yaml
pollingInterval: 10
watchers:
  - path: "/home/cian/Downloads"
    destination: "/home/cian/Documents"
    ext: ".txt"
    priority: 1
  - path: "/home/cian/Downloads"
    destination: "/home/cian/Documents/Reports"
    ext: ".txt"
    pattern: "(?i)(financial-report-[a-z]+-[0-9]+.txt)"
    priority: 2
```

`1` in this case should be the lowest priority, which all watcher will default to, and a higher priority ascending from that `2, 3, 4...`
